"""
Provenance Graph page — interactive visualization of AI decision chains.
Uses pyvis for interactive graph rendering embedded in Streamlit.
"""
import json
import os
import sys
import tempfile
from pathlib import Path

_root = Path(__file__).resolve().parent.parent.parent.parent
sys.path.insert(0, str(_root))

from dotenv import load_dotenv
load_dotenv(_root / ".env", override=True)

import httpx
import streamlit as st

st.set_page_config(
    page_title="Provenance — SENTINEL",
    layout="wide",
    initial_sidebar_state="expanded",
)

from sentinel.dashboard.theme import CUSTOM_CSS, render_sidebar_nav

st.markdown(CUSTOM_CSS, unsafe_allow_html=True)

with st.sidebar:
    st.markdown(
        '<div style="padding:14px 12px 10px;">'
        '<div style="font-size:18px;font-weight:800;color:#f8fafc;letter-spacing:-0.4px;">SENTINEL</div>'
        '<div style="font-size:12px;color:#64748b;margin-top:3px;">AI Compliance Platform</div>'
        '</div>', unsafe_allow_html=True,
    )
    st.divider()
    render_sidebar_nav(st)
    st.divider()
    st.markdown(
        '<div style="padding:2px 4px 8px;">'
        '<div style="font-size:11px;font-weight:700;color:#64748b;text-transform:uppercase;'
        'letter-spacing:0.8px;margin-bottom:5px;">Active Tenant</div>'
        f'<div style="font-size:14px;color:#e2e8f0;font-weight:600;">{os.getenv("DEMO_TENANT_ID","bank-acme")}</div>'
        '</div>', unsafe_allow_html=True,
    )

st.markdown("""
<div class="page-header">
    <h1>Provenance Graph Explorer</h1>
    <p>Visualize and verify the complete AI decision chain for any investigation case.</p>
</div>
""", unsafe_allow_html=True)

api_url   = st.session_state.get("api_url")   or os.getenv("SENTINEL_API_URL", "http://localhost:8003")
api_key   = st.session_state.get("api_key")   or os.getenv("SENTINEL_API_KEY", "")
tenant_id = st.session_state.get("tenant_id") or os.getenv("DEMO_TENANT_ID", "bank-acme")
HEADERS   = {"X-API-Key": api_key, "X-Tenant-ID": tenant_id}

COLOR_MAP = {
    "prov:Entity":   "#4299e1",   # Blue  — data artifacts / decisions
    "prov:Activity": "#48bb78",   # Green — tool calls / actions
    "prov:Agent":    "#9f7aea",   # Purple — AI agents / humans
}
LEGEND = {
    "prov:Entity":   ("Blue",   "Credit decision / case record"),
    "prov:Activity": ("Green",  "Compliance investigation run"),
    "prov:Agent":    ("Purple", "AI investigation agent"),
}


def _friendly_label(node_id: str, content: dict = None) -> str:
    """Return a short, human-readable label for a provenance node."""
    nid = node_id
    # Agent nodes  — e.g. "agent-investigation-INV-XXXX"
    if nid.startswith("agent-investigation-"):
        return "Investigation\nAgent"
    if nid.startswith("agent-"):
        name = nid.replace("agent-", "").split("-")[0].replace("_", " ").title()
        return f"{name}\nAgent"
    # Activity nodes — e.g. "activity-investigation-INV-XXXX"
    if nid.startswith("activity-investigation-"):
        inv_short = nid.split("-")[-1][:8]
        return f"Compliance\nInvestigation\n({inv_short})"
    if nid.startswith("activity-"):
        name = nid.replace("activity-", "").split("-")[0].replace("_", " ").title()
        return f"{name}\nActivity"
    # Decision / case nodes — e.g. "decision-CASE-0392"
    if nid.startswith("decision-CASE-"):
        case_num = nid.replace("decision-CASE-", "")
        outcome = ""
        if isinstance(content, dict):
            out = content.get("outcome", "")
            if out:
                outcome = f"\n{out.upper()}"
        return f"Case {case_num}{outcome}"
    if nid.startswith("tool-"):
        parts = nid.replace("tool-", "").split("-")
        return " ".join(p.replace("_", " ").title() for p in parts[:2])
    if nid.startswith("doc-"):
        return nid.replace("doc-", "").replace("_", " ").title()
    if nid.startswith("model-"):
        return nid.replace("model-", "").replace("-", " ").title()
    # Generic fallback
    parts = nid.split("-")
    return " ".join(parts[-2:]).replace("_", " ").title() if len(parts) >= 2 else nid[:20]


def _edge_label(from_type: str, to_type: str) -> str:
    """Return a readable edge relation label based on the node types it connects."""
    if from_type == "prov:Agent" and to_type == "prov:Activity":
        return "attributed to"
    if from_type == "prov:Activity" and to_type == "prov:Entity":
        return "used"
    if from_type == "prov:Entity" and to_type == "prov:Activity":
        return "generated by"
    if from_type == "prov:Agent" and to_type == "prov:Entity":
        return "attributed to"
    return "related"


def _render_graph(chain: list) -> None:
    """Render pyvis interactive graph with spread-out layout and readable fonts."""
    try:
        from pyvis.network import Network
    except ImportError:
        st.warning("pyvis not installed — showing table view instead.")
        _render_table(chain)
        return

    net = Network(
        height="560px",
        width="100%",
        bgcolor="#1e2130",
        font_color="#e2e8f0",
        directed=True,
    )

    # Physics: repulsion keeps nodes apart, spring pushes them out
    net.set_options(json.dumps({
        "physics": {
            "enabled": True,
            "solver": "repulsion",
            "repulsion": {
                "nodeDistance": 220,
                "centralGravity": 0.05,
                "springLength": 280,
                "springConstant": 0.04,
                "damping": 0.09,
            },
            "stabilization": {"iterations": 150, "updateInterval": 25},
        },
        "nodes": {
            "font": {"size": 13, "face": "Inter, sans-serif", "color": "#f1f5f9"},
            "borderWidth": 2,
            "shadow": True,
        },
        "edges": {
            "font": {"size": 11, "align": "middle", "color": "#94a3b8"},
            "color": {"color": "#475569", "highlight": "#10b981"},
            "arrows": {"to": {"enabled": True, "scaleFactor": 0.8}},
            "smooth": {"type": "curvedCW", "roundness": 0.2},
            "width": 1.5,
        },
        "interaction": {
            "hover": True,
            "tooltipDelay": 100,
            "zoomView": True,
            "dragNodes": True,
        },
    }))

    # Build node registry keyed by depth for edge wiring
    depth_to_nodes: dict = {}   # depth → list of (node_id, node_type)
    node_type_map: dict  = {}   # node_id → node_type

    for node in chain:
        nid     = node["node_id"]
        ntype   = node.get("node_type", "prov:Entity")
        d       = node.get("depth", 0)
        content = node.get("content", {})
        color   = COLOR_MAP.get(ntype, "#718096")
        label   = _friendly_label(nid, content)

        # Node size: Agent=34, Activity=40 (hub), Entity=28
        size = {"prov:Agent": 34, "prov:Activity": 40}.get(ntype, 28)

        # Tooltip — show all content fields
        tip_lines = [f"<b>{label.replace(chr(10), ' ')}</b>", f"<i>{ntype}</i>", ""]
        if isinstance(content, dict):
            for k, v in content.items():
                val = str(v)[:70] + ("…" if len(str(v)) > 70 else "")
                tip_lines.append(f"<b>{k}:</b> {val}")
        tooltip = "<br>".join(tip_lines)

        net.add_node(
            nid,
            label=label,
            color={"background": color, "border": "#cbd5e1",
                   "highlight": {"background": "#f59e0b", "border": "#ffffff"}},
            title=tooltip,
            size=size,
            mass=2,
            font={"size": 12, "multi": True},   # multi=True enables \n in labels
        )
        depth_to_nodes.setdefault(d, []).append(nid)
        node_type_map[nid] = ntype

    # Wire edges: each node at depth D connects to ALL nodes at depth D-1
    # (not just the first one — activity connects to its agent, decisions connect to activity)
    for node in chain:
        nid   = node["node_id"]
        ntype = node.get("node_type", "prov:Entity")
        d     = node.get("depth", 0)
        if d > 0:
            parents = depth_to_nodes.get(d - 1, [])
            for parent_id in parents:
                parent_type = node_type_map.get(parent_id, "prov:Entity")
                rel = _edge_label(parent_type, ntype)
                net.add_edge(
                    parent_id,
                    nid,
                    label=rel,
                    color={"color": "#475569", "highlight": "#10b981"},
                    width=1.5,
                    dashes=(ntype == "prov:Entity"),  # dashed for data edges
                )

    with tempfile.NamedTemporaryFile(suffix=".html", delete=False, mode="w", encoding="utf-8") as f:
        net.save_graph(f.name)
        html = open(f.name, encoding="utf-8").read()

    st.components.v1.html(html, height=580, scrolling=False)


def _render_table(chain: list) -> None:
    for node in chain:
        content = node.get("content", {})
        label = _friendly_label(node["node_id"], content).replace("\n", " ")
        ntype = node.get("node_type", "")
        color = COLOR_MAP.get(ntype, "#718096")
        st.markdown(
            f'<div style="background:#1e2130;border-left:4px solid {color};border-radius:8px;'
            f'padding:12px 16px;margin-bottom:8px;">'
            f'<div style="font-weight:600;color:#f1f5f9;">{label}</div>'
            f'<div style="font-size:12px;color:#94a3b8;">{ntype}</div>'
            f'<div style="font-size:12px;color:#64748b;margin-top:4px;">'
            f'{json.dumps(node.get("content",{}))[:160]}</div></div>',
            unsafe_allow_html=True,
        )


# ── Fetch recent completed investigations for the hint dropdown ─────────────────
recent_inv: list[dict] = []
try:
    _ri = httpx.get(f"{api_url}/api/v1/investigations" if False else f"{api_url}/health",
                    headers=HEADERS, timeout=3)
except Exception:
    pass

# ── Input form ─────────────────────────────────────────────────────────────────
form_col, _ = st.columns([2, 3])
with form_col:
    investigation_id = st.text_input(
        "Investigation ID",
        placeholder="e.g. INV-64B5EE4FCB12",
        help="Run an investigation first, then paste its ID here.",
    )
    case_id = st.text_input(
        "Case ID (optional)",
        placeholder="e.g. CASE-0359 — leave blank for full chain",
    )
    load_btn = st.button("Load Provenance Graph", use_container_width=True)

st.markdown("---")

if load_btn and not investigation_id:
    st.warning("Enter an Investigation ID to load its provenance graph. "
               "Run an investigation first, then copy the ID shown on the Investigate page.")
    st.stop()

if load_btn and investigation_id:
    chain = []
    report_text = None
    error_msg   = None

    with st.spinner("Loading provenance chain…"):
        try:
            resp = httpx.get(
                f"{api_url}/api/v1/provenance/{investigation_id}/trace",
                params={"case_id": case_id} if case_id else {},
                headers=HEADERS,
                timeout=15,
            )
            if resp.status_code == 200:
                data  = resp.json()
                chain = data.get("chain", [])
            else:
                error_msg = f"API returned {resp.status_code}: {resp.text[:120]}"
        except Exception as exc:
            error_msg = str(exc)

    if error_msg and not chain:
        st.error(f"Could not load provenance data: {error_msg}")
        st.info("Make sure the Investigation ID is correct. Copy it from the Investigate page after running an investigation.")
        st.stop()

    if not chain:
        st.warning("No provenance nodes found for this investigation. "
                   "Only investigations run after the latest update generate graph data.")
        st.stop()

    # Fetch report for this investigation if we have an ID
    if investigation_id:
        try:
            r2 = httpx.get(
                f"{api_url}/api/v1/investigations/{investigation_id}",
                headers=HEADERS, timeout=10,
            )
            if r2.status_code == 200:
                inv_data    = r2.json()
                report_text = inv_data.get("final_report")
        except Exception:
            pass

    # ── Graph ──────────────────────────────────────────────────────────────────
    st.markdown(f"**Decision chain — {len(chain)} nodes**")
    _render_graph(chain)

    # ── Report viewer ──────────────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### Investigation Report")
    if report_text:
        st.markdown(
            '<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;'
            'padding:20px 24px;max-height:480px;overflow-y:auto;">',
            unsafe_allow_html=True,
        )
        st.markdown(report_text)
        st.markdown("</div>", unsafe_allow_html=True)
    else:
        st.info("No report available for this investigation yet.")

    # ── Node detail cards ──────────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### Node Details")
    for node in chain:
        content = node.get("content", {})
        label   = _friendly_label(node["node_id"], content).replace("\n", " ")
        ntype   = node.get("node_type", "")
        color   = COLOR_MAP.get(ntype, "#718096")
        with st.expander(f"{label}  ({ntype})"):
            if isinstance(content, dict) and content:
                cols = st.columns(2)
                items = list(content.items())
                for i, (k, v) in enumerate(items):
                    with cols[i % 2]:
                        st.markdown(f"**{k}**")
                        st.code(str(v), language=None)
            else:
                st.json(content)
            h = content.get("content_hash", "") if isinstance(content, dict) else ""
            if h:
                st.caption(f"SHA-256: {h}")

# ── Legend ─────────────────────────────────────────────────────────────────────
st.markdown("---")
leg_cols = st.columns(3)
for col, (ntype, (color_name, desc)) in zip(leg_cols, LEGEND.items()):
    with col:
        dot_color = COLOR_MAP[ntype]
        st.markdown(
            f'<div style="display:flex;align-items:center;gap:8px;font-size:14px;">'
            f'<span style="width:12px;height:12px;border-radius:50%;background:{dot_color};'
            f'flex-shrink:0;display:inline-block;"></span>'
            f'<span><strong>{color_name}</strong> — {desc}</span></div>',
            unsafe_allow_html=True,
        )
