"""
Provenance Graph page — interactive visualization of AI decision chains.
Uses pyvis for interactive graph rendering embedded in Streamlit.
"""
import json
import os
import sys
import tempfile
from pathlib import Path

_root = Path(__file__).resolve().parent.parent.parent.parent
sys.path.insert(0, str(_root))

from dotenv import load_dotenv
load_dotenv(_root / ".env", override=True)

import httpx
import streamlit as st

st.set_page_config(
    page_title="Provenance — SENTINEL",
    layout="wide",
    initial_sidebar_state="expanded",
)

from sentinel.dashboard.theme import CUSTOM_CSS, render_sidebar_nav

st.markdown(CUSTOM_CSS, unsafe_allow_html=True)

with st.sidebar:
    st.markdown(
        '<div style="padding:14px 12px 10px;">'
        '<div style="font-size:18px;font-weight:800;color:#f8fafc;letter-spacing:-0.4px;">SENTINEL</div>'
        '<div style="font-size:12px;color:#64748b;margin-top:3px;">AI Compliance Platform</div>'
        '</div>', unsafe_allow_html=True,
    )
    st.divider()
    render_sidebar_nav(st)
    st.divider()
    st.markdown(
        '<div style="padding:2px 4px 8px;">'
        '<div style="font-size:11px;font-weight:700;color:#64748b;text-transform:uppercase;'
        'letter-spacing:0.8px;margin-bottom:5px;">Active Tenant</div>'
        f'<div style="font-size:14px;color:#e2e8f0;font-weight:600;">{os.getenv("DEMO_TENANT_ID","bank-acme")}</div>'
        '</div>', unsafe_allow_html=True,
    )

st.markdown("""
<div class="page-header">
    <h1>Provenance Graph Explorer</h1>
    <p>Visualize and verify the complete AI decision chain for any investigation case.</p>
</div>
""", unsafe_allow_html=True)

api_url   = st.session_state.get("api_url")   or os.getenv("SENTINEL_API_URL", "http://localhost:8003")
api_key   = st.session_state.get("api_key")   or os.getenv("SENTINEL_API_KEY", "")
tenant_id = st.session_state.get("tenant_id") or os.getenv("DEMO_TENANT_ID", "bank-acme")
HEADERS   = {"X-API-Key": api_key, "X-Tenant-ID": tenant_id}

COLOR_MAP = {
    "prov:Entity":   "#4299e1",   # Blue  — data artifacts / decisions
    "prov:Activity": "#48bb78",   # Green — tool calls / actions
    "prov:Agent":    "#9f7aea",   # Purple — AI agents / humans
}
LEGEND = {
    "prov:Entity":   ("Blue",   "Credit decision / case record"),
    "prov:Activity": ("Green",  "Compliance investigation run"),
    "prov:Agent":    ("Purple", "AI investigation agent"),
}


def _friendly_label(node_id: str, content: dict = None) -> str:
    """Return a short, human-readable label for a provenance node."""
    nid = node_id
    # Agent nodes  — e.g. "agent-investigation-INV-XXXX"
    if nid.startswith("agent-investigation-"):
        return "Investigation\nAgent"
    if nid.startswith("agent-"):
        name = nid.replace("agent-", "").split("-")[0].replace("_", " ").title()
        return f"{name}\nAgent"
    # Activity nodes — e.g. "activity-investigation-INV-XXXX"
    if nid.startswith("activity-investigation-"):
        inv_short = nid.split("-")[-1][:8]
        return f"Compliance\nInvestigation\n({inv_short})"
    if nid.startswith("activity-"):
        name = nid.replace("activity-", "").split("-")[0].replace("_", " ").title()
        return f"{name}\nActivity"
    # Decision / case nodes — e.g. "decision-CASE-0392"
    if nid.startswith("decision-CASE-"):
        case_num = nid.replace("decision-CASE-", "")
        outcome = ""
        if isinstance(content, dict):
            out = content.get("outcome", "")
            if out:
                outcome = f"\n{out.upper()}"
        return f"Case {case_num}{outcome}"
    if nid.startswith("tool-"):
        parts = nid.replace("tool-", "").split("-")
        return " ".join(p.replace("_", " ").title() for p in parts[:2])
    if nid.startswith("doc-"):
        return nid.replace("doc-", "").replace("_", " ").title()
    if nid.startswith("model-"):
        return nid.replace("model-", "").replace("-", " ").title()
    # Generic fallback
    parts = nid.split("-")
    return " ".join(parts[-2:]).replace("_", " ").title() if len(parts) >= 2 else nid[:20]


def _edge_label(from_type: str, to_type: str) -> str:
    """Return a readable edge relation label based on the node types it connects."""
    if from_type == "prov:Agent" and to_type == "prov:Activity":
        return "attributed to"
    if from_type == "prov:Activity" and to_type == "prov:Entity":
        return "used"
    if from_type == "prov:Entity" and to_type == "prov:Activity":
        return "generated by"
    if from_type == "prov:Agent" and to_type == "prov:Entity":
        return "attributed to"
    return "related"


def _render_graph(chain: list) -> None:
    """Render pyvis interactive graph with spread-out layout and readable fonts."""
    try:
        from pyvis.network import Network
    except ImportError:
        st.warning("pyvis not installed — showing table view instead.")
        _render_table(chain)
        return

    net = Network(
        height="560px",
        width="100%",
        bgcolor="#1e2130",
        font_color="#e2e8f0",
        directed=True,
    )

    # Physics: repulsion keeps nodes apart, spring pushes them out
    net.set_options(json.dumps({
        "physics": {
            "enabled": True,
            "solver": "repulsion",
            "repulsion": {
                "nodeDistance": 220,
                "centralGravity": 0.05,
                "springLength": 280,
                "springConstant": 0.04,
                "damping": 0.09,
            },
            "stabilization": {"iterations": 150, "updateInterval": 25},
        },
        "nodes": {
            "font": {"size": 13, "face": "Inter, sans-serif", "color": "#f1f5f9"},
            "borderWidth": 2,
            "shadow": True,
        },
        "edges": {
            "font": {"size": 11, "align": "middle", "color": "#94a3b8"},
            "color": {"color": "#475569", "highlight": "#10b981"},
            "arrows": {"to": {"enabled": True, "scaleFactor": 0.8}},
            "smooth": {"type": "curvedCW", "roundness": 0.2},
            "width": 1.5,
        },
        "interaction": {
            "hover": True,
            "tooltipDelay": 100,
            "zoomView": True,
            "dragNodes": True,
        },
    }))

    # Build node registry keyed by depth for edge wiring
    depth_to_nodes: dict = {}   # depth → list of (node_id, node_type)
    node_type_map: dict  = {}   # node_id → node_type

    for node in chain:
        nid     = node["node_id"]
        ntype   = node.get("node_type", "prov:Entity")
        d       = node.get("depth", 0)
        content = node.get("content", {})
        color   = COLOR_MAP.get(ntype, "#718096")
        label   = _friendly_label(nid, content)

        # Enhance label with useful metrics
        enhanced_label_parts = [label]

        if isinstance(content, dict):
            # Add verdict if available
            if "compliance_verdict" in content:
                enhanced_label_parts.append(f"Verdict: {content['compliance_verdict']}")
            # Add risk if available
            if "regulatory_risk" in content:
                enhanced_label_parts.append(f"Risk: {content['regulatory_risk']}")
            # Add case count for agent/activity nodes
            if "cases_analyzed" in content:
                enhanced_label_parts.append(f"Cases: {content['cases_analyzed']}")
            # Add evidence count
            if "evidence_count" in content:
                enhanced_label_parts.append(f"Evidence: {content['evidence_count']}")
            # Add denial/approval breakdown
            if "denied_count" in content and "approved_count" in content:
                enhanced_label_parts.append(f"Denied: {content['denied_count']}, Approved: {content['approved_count']}")

        enhanced_label = "\n".join(enhanced_label_parts[:3])  # Limit to 3 lines for readability

        # Determine color based on verdict if available
        node_color = color
        if isinstance(content, dict):
            verdict = content.get("compliance_verdict", "").upper()
            if verdict == "COMPLIANT":
                node_color = "#10b981"  # Green
            elif verdict == "VIOLATION":
                node_color = "#ef4444"  # Red
            elif verdict == "UNCERTAIN":
                node_color = "#f59e0b"  # Amber

        # Node size: Agent=40, Activity=50 (hub), Entity=32
        size = {"prov:Agent": 40, "prov:Activity": 50}.get(ntype, 32)

        # Add more weight to important nodes
        if isinstance(content, dict) and content.get("cases_analyzed", 0) > 0:
            size += 5

        # Enhanced tooltip — show key fields
        tip_lines = [f"<b>{label.replace(chr(10), ' ')}</b>", f"<i>{ntype}</i>", ""]
        if isinstance(content, dict):
            # Show key fields first
            key_fields = ["compliance_verdict", "regulatory_risk", "cases_analyzed", "evidence_count",
                         "denied_count", "approved_count", "case_ids", "content_hash"]
            for k in key_fields:
                if k in content:
                    val = str(content[k])[:70] + ("…" if len(str(content[k])) > 70 else "")
                    tip_lines.append(f"<b>{k}:</b> {val}")
            # Show other fields
            for k, v in content.items():
                if k not in key_fields:
                    val = str(v)[:70] + ("…" if len(str(v)) > 70 else "")
                    tip_lines.append(f"<b>{k}:</b> {val}")
        tooltip = "<br>".join(tip_lines)

        net.add_node(
            nid,
            label=enhanced_label,
            color={"background": node_color, "border": "#cbd5e1",
                   "highlight": {"background": "#fbbf24", "border": "#ffffff"}},
            title=tooltip,
            size=size,
            mass=3,
            font={"size": 11, "multi": True},   # multi=True enables \n in labels
            borderWidth=2,
        )
        depth_to_nodes.setdefault(d, []).append(nid)
        node_type_map[nid] = ntype

    # Wire edges: each node at depth D connects to ALL nodes at depth D-1
    # (not just the first one — activity connects to its agent, decisions connect to activity)
    for node in chain:
        nid   = node["node_id"]
        ntype = node.get("node_type", "prov:Entity")
        d     = node.get("depth", 0)
        if d > 0:
            parents = depth_to_nodes.get(d - 1, [])
            for parent_id in parents:
                parent_type = node_type_map.get(parent_id, "prov:Entity")
                rel = _edge_label(parent_type, ntype)
                net.add_edge(
                    parent_id,
                    nid,
                    label=rel,
                    color={"color": "#475569", "highlight": "#10b981"},
                    width=1.5,
                    dashes=(ntype == "prov:Entity"),  # dashed for data edges
                )

    with tempfile.NamedTemporaryFile(suffix=".html", delete=False, mode="w", encoding="utf-8") as f:
        net.save_graph(f.name)
        html = open(f.name, encoding="utf-8").read()

    st.components.v1.html(html, height=580, scrolling=False)


def _render_table(chain: list) -> None:
    for node in chain:
        content = node.get("content", {})
        label = _friendly_label(node["node_id"], content).replace("\n", " ")
        ntype = node.get("node_type", "")
        color = COLOR_MAP.get(ntype, "#718096")
        st.markdown(
            f'<div style="background:#1e2130;border-left:4px solid {color};border-radius:8px;'
            f'padding:12px 16px;margin-bottom:8px;">'
            f'<div style="font-weight:600;color:#f1f5f9;">{label}</div>'
            f'<div style="font-size:12px;color:#94a3b8;">{ntype}</div>'
            f'<div style="font-size:12px;color:#64748b;margin-top:4px;">'
            f'{json.dumps(node.get("content",{}))[:160]}</div></div>',
            unsafe_allow_html=True,
        )


# ── Fetch recent completed investigations for the hint dropdown ─────────────────
recent_inv: list[dict] = []
try:
    _ri = httpx.get(f"{api_url}/api/v1/investigations" if False else f"{api_url}/health",
                    headers=HEADERS, timeout=3)
except Exception:
    pass

# ── Input form ─────────────────────────────────────────────────────────────────
# Check if Investigation ID was passed from Results page
passed_inv_id = st.session_state.get("provenance_inv_id", "")

form_col, _ = st.columns([2, 3])
with form_col:
    investigation_id = st.text_input(
        "Investigation ID",
        value=passed_inv_id,
        placeholder="e.g. INV-64B5EE4FCB12",
        help="Enter investigation ID or navigate from Results page",
    )
    case_id = st.text_input(
        "Case ID (optional)",
        placeholder="e.g. CASE-0359 — leave blank for full chain",
        help="Enter a specific case ID to focus the graph on that case",
    )
    load_btn = st.button("Load Provenance Graph", use_container_width=True)

st.markdown("---")

# Auto-load if passed_inv_id exists
auto_load = passed_inv_id and not st.session_state.get("provenance_loaded", False)
if auto_load:
    load_btn = True
    st.session_state.provenance_loaded = True

if load_btn and not investigation_id:
    st.warning("Enter an Investigation ID to load its provenance graph. "
               "Run an investigation first, then copy the ID shown on the Investigate page.")
    st.stop()

if load_btn and investigation_id:
    chain = []
    report_text = None
    inv_data = {}
    error_msg   = None

    # Use case_id from session state if it was set by button click
    final_case_id = case_id or st.session_state.get("case_id_for_api", "")

    # Show what we're loading
    if final_case_id:
        st.info(f"Loading provenance for case: **{final_case_id}**")
    else:
        st.info("Loading full provenance chain...")

    with st.spinner("Loading provenance chain…"):
        try:
            api_params = {"case_id": final_case_id} if final_case_id else {}
            resp = httpx.get(
                f"{api_url}/api/v1/provenance/{investigation_id}/trace",
                params=api_params,
                headers=HEADERS,
                timeout=15,
            )
            if resp.status_code == 200:
                data  = resp.json()
                chain = data.get("chain", [])
            else:
                error_msg = f"API returned {resp.status_code}: {resp.text[:120]}"
        except Exception as exc:
            error_msg = str(exc)

    if error_msg and not chain:
        st.error(f"Could not load provenance data: {error_msg}")
        st.info("Make sure the Investigation ID is correct. Copy it from the Investigate page after running an investigation.")
        st.stop()

    if not chain:
        if case_id:
            st.warning(f"No provenance nodes found for case **{case_id}** in this investigation. "
                       f"Try loading the full chain (leave Case ID blank) to see all cases.")
        else:
            st.warning("No provenance nodes found for this investigation. "
                       "Only investigations run after the latest update generate graph data.")
        st.stop()

    # Fetch investigation data for report and summary
    inv_verdict = None
    inv_risk = None
    inv_evidence_count = None
    inv_case_count = None

    if investigation_id:
        try:
            r2 = httpx.get(
                f"{api_url}/api/v1/investigations/{investigation_id}",
                headers=HEADERS, timeout=10,
            )
            if r2.status_code == 200:
                inv_data    = r2.json()
                report_text = inv_data.get("final_report")

                # Extract verdict and risk from top-level fields (not state_snapshot)
                inv_verdict = inv_data.get("compliance_verdict", "N/A")
                inv_risk = inv_data.get("regulatory_risk", "N/A")
                inv_evidence_count = inv_data.get("evidence_count", 0)
                inv_case_count = inv_data.get("case_count", 0)
        except Exception:
            pass

    # ── Graph ──────────────────────────────────────────────────────────────────
    if case_id:
        st.info(f"Showing nodes for case **{case_id}** ({len(chain)} nodes)")
    else:
        st.markdown(f"**Decision chain — {len(chain)} nodes**")

    if case_id and len(chain) == 0:
        st.warning("No nodes found for this case. Try viewing the full chain to see available cases.")
    else:
        _render_graph(chain)

        # ── Graph Summary Panel ────────────────────────────────────────────────────────
        st.markdown("---")
        st.markdown("**Provenance Graph Summary**")

        # Calculate statistics from chain
        agent_nodes = [n for n in chain if n.get("node_type") == "prov:Agent"]
        activity_nodes = [n for n in chain if n.get("node_type") == "prov:Activity"]
        case_nodes = [n for n in chain if n.get("node_type") == "prov:Entity"]

        col1, col2, col3, col4 = st.columns(4)

        with col1:
            st.metric("Total Nodes", len(chain))
        with col2:
            st.metric("Agents", len(agent_nodes))
        with col3:
            st.metric("Activities", len(activity_nodes))
        with col4:
            st.metric("Cases/Data", len(case_nodes))

        # Show key metrics from the main activity node if available
        if activity_nodes and activity_nodes[0].get("content"):
            content = activity_nodes[0]["content"]
            st.markdown("**Investigation Details:**")

            col1, col2, col3 = st.columns(3)
            with col1:
                cases = content.get("cases_analyzed", 0)
                st.metric("Cases Analyzed", cases)
            with col2:
                denied = content.get("denied_count", 0)
                approved = content.get("approved_count", 0)
                st.metric("Denied/Approved", f"{denied}/{approved}")
            with col3:
                evidence = content.get("evidence_count", 0)
                st.metric("Evidence Items", evidence)

    # ── Report viewer ──────────────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### Investigation Report")
    if report_text:
        st.markdown(
            '<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;'
            'padding:20px 24px;max-height:480px;overflow-y:auto;">',
            unsafe_allow_html=True,
        )
        st.markdown(report_text)
        st.markdown("</div>", unsafe_allow_html=True)
    else:
        st.info("No report available for this investigation yet.")

    # ── Decision Chain Analysis ────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### Decision Chain Summary")

    # Show investigation-level verdict and risk first
    if inv_verdict or inv_risk or inv_case_count or inv_evidence_count:
        col1, col2, col3 = st.columns([1, 1, 1])
        with col1:
            st.metric("Verdict", inv_verdict or "N/A")
        with col2:
            st.metric("Risk Level", inv_risk or "N/A")
        with col3:
            st.metric("Cases Reviewed", inv_case_count or 0)
        st.divider()

    # Build phase timeline from agent events (which have better data than provenance nodes)
    agent_events = inv_data.get("agent_events", []) if inv_data else []

    if agent_events:
        st.markdown("**Phase Timeline:**")
        for idx, event in enumerate(agent_events):
            agent = event.get("agent", "Unknown").replace("_", " ").title()
            event_type = event.get("event", "")
            status_text = "Completed" if event_type == "complete" else event_type.title()

            # Simple clean layout
            col1, col2 = st.columns([3, 1])
            with col1:
                st.markdown(f"**{agent}**")
            with col2:
                st.markdown(status_text)
            st.divider()
    else:
        # Fallback to provenance nodes if no agent events
        decision_chain_details = []
        for node in chain:
            nid = node.get("node_id", "")
            content = node.get("content", {})
            ntype = node.get("node_type", "")

            if ntype == "prov:Agent" or ntype == "prov:Activity":
                agent_name = _friendly_label(nid, content).replace("\n", " ")
                timestamp = content.get("timestamp", content.get("created_at", "N/A"))
                status = content.get("status", content.get("phase", "N/A"))
                decision_chain_details.append({
                    "Agent/Phase": agent_name,
                    "Timestamp": timestamp,
                    "Status": status,
                    "Details": content
                })

        if decision_chain_details:
            st.markdown("**Phase Timeline:**")
            for idx, item in enumerate(decision_chain_details):
                # Simple clean layout
                col1, col2 = st.columns([3, 1])
                with col1:
                    st.markdown(f"**{item['Agent/Phase']}**")
                with col2:
                    st.markdown(item['Status'].title())
                st.divider()
        else:
            st.info("No decision chain details found in graph.")

    # ── Evidence Items Analysis ────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### Evidence Items")

    # Show evidence summary from investigation state
    if inv_evidence_count and inv_evidence_count > 0:
        st.metric("Total Evidence Items Found", inv_evidence_count)
        st.info(f"Investigation identified {inv_evidence_count} evidence items supporting the compliance analysis.")
        evidence_found = True
    elif inv_case_count and inv_case_count > 0:
        st.metric("Cases Analyzed for Evidence", inv_case_count)
        evidence_found = False
    else:
        evidence_found = False

    # Only search for detailed evidence items in provenance nodes if we haven't already shown them
    if not evidence_found:
        for node in chain:
            content = node.get("content", {})

            # Check for evidence items in various formats
            evidence_items = content.get("evidence_items", [])
            if isinstance(evidence_items, str):
                try:
                    evidence_items = json.loads(evidence_items)
                except:
                    evidence_items = []

            if evidence_items and isinstance(evidence_items, list) and len(evidence_items) > 0:
                evidence_found = True
                for ev in evidence_items:
                    if isinstance(ev, dict):
                        ev_id = ev.get("id", ev.get("evidence_id", "Unknown"))
                        description = ev.get("description", ev.get("finding", "No description"))
                        source = ev.get("source", ev.get("source_type", "N/A"))
                        trust_score = ev.get("trust_score", ev.get("confidence", "N/A"))

                        with st.container():
                            st.markdown(f"**Evidence ID:** {ev_id}")
                            st.markdown(f"**Description:** {description}")
                            col1, col2 = st.columns(2)
                            with col1:
                                st.markdown(f"**Source:** {source}")
                            with col2:
                                trust_val = trust_score if isinstance(trust_score, (int, float)) else "Unknown"
                                if isinstance(trust_val, (int, float)):
                                    st.progress(float(trust_val) if 0 <= float(trust_val) <= 1 else 0.5,
                                               text=f"Trust Score: {trust_val}")
                                else:
                                    st.caption(f"Trust Score: {trust_val}")
                            st.divider()

        if not evidence_found:
            st.info("No evidence items found in this investigation.")

    # ── Source Documentation ───────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### Source Documentation")

    # ── Investigation Source Summary ──────────────────────────────────────────
    sources_found = False
    case_count = 0
    regulations = []

    for node in chain:
        content = node.get("content", {})

        # Extract source information from nodes
        node_case_ids = content.get("case_ids", [])
        node_regulations = content.get("applicable_regulations", content.get("regulations", []))

        if isinstance(node_case_ids, str):
            try:
                node_case_ids = json.loads(node_case_ids)
            except:
                node_case_ids = []

        if isinstance(node_regulations, str):
            try:
                node_regulations = json.loads(node_regulations)
            except:
                node_regulations = []

        if node_case_ids:
            case_count = max(case_count, len(node_case_ids))
            sources_found = True

        if node_regulations:
            regulations.extend(node_regulations)
            sources_found = True

    if sources_found:
        col1, col2 = st.columns(2)
        with col1:
            if case_count > 0:
                st.metric("Cases Analyzed", case_count)
        with col2:
            if regulations:
                st.metric("Regulations Referenced", len(set(regulations)))
    else:
        st.info("No source documentation found in this investigation.")

    # ── Provenance Integrity ──────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### Provenance Integrity")

    # Count nodes with integrity verification
    verified_nodes = 0
    for node in chain:
        content = node.get("content", {})
        if content.get("content_hash"):
            verified_nodes += 1

    if verified_nodes > 0:
        st.success(f"✓ **{verified_nodes} nodes verified** — All provenance records include integrity hashes for tamper detection.")
    else:
        st.info("No integrity verification data available for this investigation.")

    st.markdown("---")
    st.markdown("**Audit Trail:** All decisions, timestamps, and evidence items are cryptographically signed and stored in the provenance database for complete audit compliance.")

    # ── Node detail cards ──────────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### Detailed Node Information")
    for node in chain:
        content = node.get("content", {})
        label   = _friendly_label(node["node_id"], content).replace("\n", " ")
        ntype   = node.get("node_type", "")
        color   = COLOR_MAP.get(ntype, "#718096")
        with st.expander(f"{label}  ({ntype})"):
            if isinstance(content, dict) and content:
                cols = st.columns(2)
                items = list(content.items())
                for i, (k, v) in enumerate(items):
                    with cols[i % 2]:
                        st.markdown(f"**{k}**")
                        st.code(str(v), language=None)
            else:
                st.json(content)
            h = content.get("content_hash", "") if isinstance(content, dict) else ""
            if h:
                st.caption(f"SHA-256: {h}")

# ── Legend ─────────────────────────────────────────────────────────────────────
st.markdown("---")
leg_cols = st.columns(3)
for col, (ntype, (color_name, desc)) in zip(leg_cols, LEGEND.items()):
    with col:
        dot_color = COLOR_MAP[ntype]
        st.markdown(
            f'<div style="display:flex;align-items:center;gap:8px;font-size:14px;">'
            f'<span style="width:12px;height:12px;border-radius:50%;background:{dot_color};'
            f'flex-shrink:0;display:inline-block;"></span>'
            f'<span><strong>{color_name}</strong> — {desc}</span></div>',
            unsafe_allow_html=True,
        )
