"""
W3C PROV-O dataclasses for SENTINEL provenance records.

PROV-O defines three core types:
  Entity   — a thing (decision, document, dataset)
  Activity — something that happened (tool call, agent reasoning step)
  Agent    — something that caused the activity (AI agent, human, system)

We extend these minimally to add SENTINEL-specific fields (tenant_id, content_hash).
The JSON representation is W3C PROV-O compatible for regulator export.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum


class NodeType(str, Enum):
    """Maps to W3C PROV-O types — stored as string for JSON compatibility."""
    ENTITY = "prov:Entity"           # A data artifact (decision, document, chunk)
    ACTIVITY = "prov:Activity"       # An action (tool call, retrieval, generation)
    AGENT = "prov:Agent"             # An actor (AI agent, human reviewer)


class RelationType(str, Enum):
    """W3C PROV-O relations between nodes."""
    WAS_GENERATED_BY = "prov:wasGeneratedBy"     # Entity generated by Activity
    USED = "prov:used"                             # Activity used Entity
    WAS_ATTRIBUTED_TO = "prov:wasAttributedTo"    # Entity attributed to Agent
    WAS_INFORMED_BY = "prov:wasInformedBy"        # Activity informed by Activity
    WAS_DERIVED_FROM = "prov:wasDerivedFrom"      # Entity derived from Entity


@dataclass
class ProvNode:
    """
    A single node in the provenance graph.
    content_hash is SHA-256 of the node's content — enables tamper detection.
    tenant_id enforces data isolation: nodes are never shared across tenants.
    """
    node_id: str
    node_type: NodeType
    tenant_id: str
    content: dict                      # Domain-specific payload
    content_hash: str = field(init=False)
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    metadata: dict = field(default_factory=dict)

    def __post_init__(self):
        # Hash computed from content — any modification changes the hash
        content_bytes = json.dumps(self.content, sort_keys=True).encode("utf-8")
        self.content_hash = hashlib.sha256(content_bytes).hexdigest()

    def to_prov_json(self) -> dict:
        """Export as W3C PROV-O JSON — suitable for regulator submission."""
        return {
            "@id": f"sentinel://{self.tenant_id}/{self.node_id}",
            "prov:id": self.node_id,
            "@type": self.node_type.value,
            "prov:type": self.node_type.value,
            "prov:generatedAtTime": self.timestamp,
            "content_hash": self.content_hash,
            "sentinel:contentHash": self.content_hash,
            "sentinel:tenantId": self.tenant_id,
            **self.content,
        }


@dataclass
class ProvEdge:
    """
    A directed relationship between two provenance nodes.
    Maps to W3C PROV-O relations (wasGeneratedBy, used, wasDerivedFrom, etc.).
    """
    edge_id: str
    source_id: str         # The node that is the subject of the relation
    target_id: str         # The node that is the object of the relation
    relation: RelationType
    tenant_id: str
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    metadata: dict = field(default_factory=dict)

    def to_prov_json(self) -> dict:
        return {
            "@type": self.relation.value,
            "prov:subject": f"sentinel://{self.tenant_id}/{self.source_id}",
            "prov:object": f"sentinel://{self.tenant_id}/{self.target_id}",
            "prov:time": self.timestamp,
        }


def make_decision_node(
    case_id: str, tenant_id: str, outcome: str, model_version: str,
    timestamp: str, reasoning_summary: str = "",
) -> ProvNode:
    """Factory for a decision entity node."""
    return ProvNode(
        node_id=f"decision-{case_id}",
        node_type=NodeType.ENTITY,
        tenant_id=tenant_id,
        content={
            "case_id": case_id,
            "outcome": outcome,
            "model_version": model_version,
            # Store summary — full reasoning stored separately, not in provenance graph
            "reasoning_summary": reasoning_summary[:500],
            "timestamp": timestamp,
        },
    )


def make_agent_node(agent_name: str, tenant_id: str, investigation_id: str) -> ProvNode:
    """Factory for an AI agent actor node."""
    return ProvNode(
        node_id=f"agent-{agent_name}-{investigation_id}",
        node_type=NodeType.AGENT,
        tenant_id=tenant_id,
        content={"agent_name": agent_name, "investigation_id": investigation_id},
    )


def make_tool_call_node(
    tool_name: str,
    tenant_id: str,
    inputs: dict | None = None,
    outputs: dict | None = None,
    inputs_summary: str = "",
    outputs_summary: str = "",
    investigation_id: str = "",
) -> ProvNode:
    """Factory for a tool call activity node."""
    # Accept either dict inputs/outputs or string summaries
    in_summary = str(inputs)[:200] if inputs is not None else inputs_summary[:200]
    out_summary = str(outputs)[:200] if outputs is not None else outputs_summary[:200]
    node_suffix = investigation_id or f"{datetime.now().timestamp():.0f}"
    return ProvNode(
        node_id=f"tool-{tool_name}-{node_suffix}",
        node_type=NodeType.ACTIVITY,
        tenant_id=tenant_id,
        content={
            "tool_name": tool_name,
            "inputs_summary": in_summary,
            "outputs_summary": out_summary,
            "investigation_id": investigation_id,
        },
    )
