"""
chunker.py — Split extracted document content into chunks for embedding.

Why different strategies per content type?

  TEXT   → Semantic chunking (experiment winner C4, score 5.0)
           Splits where topic changes, keeps related sentences together.
           Fixed-512 also scored 5.0 but semantic handles variable-length
           engineering content better (short procedure steps + long descriptions).

  TABLES → Split every TABLE_CHUNK_ROWS rows (header repeated in each split).
           Large tables with 20+ rows dilute embeddings — splitting into 6-row
           groups makes each chunk specific to one fact/spec range.

  IMAGES → One chunk per image caption (generated by image_captioner.py)
           The caption IS the chunk — no further splitting needed.

CONTEXTUAL RETRIEVAL (Anthropic technique):
  Every chunk is prefixed with a 1-sentence document context before embedding:
    "[pump_maintenance_manual.pdf — Section: Safety Instructions, p.12]"
  This anchors the embedding to the engineering domain and dramatically
  improves retrieval precision for domain-specific queries.

Output: list of dicts with keys:
  content    : the text to embed (contextualised)
  chunk_type : 'text' | 'table' | 'image'
  page       : page number in source document
  section    : extracted section heading (best-effort)
  image_path : path to saved image file (only for chunk_type='image')
"""

import logging
import re
from pathlib import Path

logger = logging.getLogger(__name__)

from langchain_experimental.text_splitter import SemanticChunker
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.documents import Document

from configs.settings import (
    EMBED_MODEL,
    SEMANTIC_BREAKPOINT_TYPE,
    SEMANTIC_BREAKPOINT_THRESHOLD,
    PII_REDACTION_ENABLED,
)
from src.ingest.document_parser import ParsedDocument

# Max rows per table chunk — large tables are split into groups of this size
# with the header row repeated in each group so every chunk is self-contained.
TABLE_CHUNK_ROWS = 6


def chunk_document(
    parsed_doc: ParsedDocument,
    image_captions: list[dict],
    image_save_dir: Path,
) -> list[dict]:
    """
    Convert a ParsedDocument into a flat list of chunks ready for embedding.

    Args:
        parsed_doc     : output from document_parser.parse_document()
        image_captions : list of {page, index, caption} from image_captioner.py
                         Pass [] if skipping image captioning.
        image_save_dir : directory where image files were saved (for image_path)

    Returns:
        list of chunk dicts, each with keys:
          content, chunk_type, page, section, image_path (None for non-images)
    """
    chunks = []

    # ── 1. Semantic chunks from text ──────────────────────────────────────
    text_chunks = _chunk_text(parsed_doc)
    chunks.extend(text_chunks)

    # ── 2. Table chunks (split every TABLE_CHUNK_ROWS rows) ───────────────
    table_chunks = _chunk_tables(parsed_doc)
    chunks.extend(table_chunks)

    # ── 3. Image caption chunks ───────────────────────────────────────────
    image_chunks = _chunk_images(image_captions, image_save_dir)
    chunks.extend(image_chunks)

    logger.info("Chunked '%s': text=%d table=%d image=%d total=%d",
                parsed_doc.filename, len(text_chunks), len(table_chunks), len(image_chunks), len(chunks))
    return chunks


def _make_context_prefix(filename: str, page: int, section: str) -> str:
    """
    Build the contextual prefix prepended to every chunk before embedding.

    Anchors the chunk to its document, page, and section so the embedding
    carries domain-specific signal even for short or ambiguous text.
    """
    parts = [f"[{filename}"]
    if section:
        parts.append(f" — {section}")
    parts.append(f", p.{page}]")
    return "".join(parts)


def _contextualise(content: str, filename: str, page: int, section: str) -> str:
    """Prepend document context to chunk content before embedding."""
    prefix = _make_context_prefix(filename, page, section)
    return f"{prefix}\n{content}"


def _chunk_text(parsed_doc: ParsedDocument) -> list[dict]:
    """
    Apply SemanticChunker to full document text with parent-child chunking.

    Parent-child strategy:
      - First pass: split into large parent chunks (~3 semantic segments grouped)
      - Second pass: split each parent into smaller child chunks
      - Child chunk is embedded (small = precise retrieval)
      - Parent content is stored alongside child (large = rich generation context)

    This gives the best of both: precise retrieval + full context for the LLM.
    """
    page_separator = "\n\n---PAGE_BREAK---\n\n"
    page_texts = []
    page_nums  = []

    for page_data in parsed_doc.all_text_blocks:
        if page_data["text"].strip():
            page_texts.append(page_data["text"])
            page_nums.append(page_data["page"])

    if not page_texts:
        return []

    full_text = page_separator.join(page_texts)

    # Child splitter: fine-grained for precise retrieval
    child_splitter = SemanticChunker(
        embeddings=HuggingFaceEmbeddings(model_name=EMBED_MODEL, model_kwargs={"device": "cpu"}),
        breakpoint_threshold_type=SEMANTIC_BREAKPOINT_TYPE,
        breakpoint_threshold_amount=SEMANTIC_BREAKPOINT_THRESHOLD,
    )

    # Parent splitter: coarser — groups ~3 semantic sections together
    parent_splitter = SemanticChunker(
        embeddings=HuggingFaceEmbeddings(model_name=EMBED_MODEL, model_kwargs={"device": "cpu"}),
        breakpoint_threshold_type=SEMANTIC_BREAKPOINT_TYPE,
        breakpoint_threshold_amount=75,
    )

    parent_docs = parent_splitter.create_documents([full_text])
    chunks = []

    for parent_doc in parent_docs:
        parent_text = parent_doc.page_content.strip()
        if len(parent_text) < 50:
            continue

        # Split parent into children
        child_docs = child_splitter.create_documents([parent_text])

        for child_doc in child_docs:
            child_text = child_doc.page_content.strip()
            if len(child_text) < 50:
                continue

            if PII_REDACTION_ENABLED:
                from src.guardrails.pii_detector import redact_pii
                child_text = redact_pii(child_text)

            page    = _estimate_page(child_text, page_texts, page_nums)
            section = _extract_section_heading(child_text)

            # Child content (small, precise) is what gets embedded
            child_contextualised = _contextualise(child_text, parsed_doc.filename, page, section)
            # Parent content (large) is what the LLM sees during generation
            parent_contextualised = _contextualise(parent_text, parsed_doc.filename, page, section)

            chunks.append({
                "content":        child_contextualised,   # embedded for retrieval
                "parent_content": parent_contextualised,  # returned to LLM for generation
                "chunk_type":     "text",
                "page":           page,
                "section":        section,
                "image_path":     None,
            })

    return chunks


def _chunk_tables(parsed_doc: ParsedDocument) -> list[dict]:
    """
    Convert each extracted table into row-group chunks.

    Large tables (>TABLE_CHUNK_ROWS rows) are split into groups of TABLE_CHUNK_ROWS
    with the header row repeated in each group. This ensures each chunk contains
    a dense, specific set of values rather than diluting a 20-row table into one
    vague embedding.

    Each chunk is contextualised with doc/page metadata before embedding.
    """
    chunks = []
    for tbl in parsed_doc.all_tables:
        caption  = tbl["caption"]
        markdown = tbl["markdown"]
        page     = tbl["page"]

        # Parse the markdown back into rows for splitting
        md_rows = [r for r in markdown.split("\n") if r.strip()]

        # Identify header row and separator row
        if len(md_rows) < 2:
            # Too small to split — keep as-is
            content = _contextualise(
                f"{caption}\n\n{markdown}", parsed_doc.filename, page, caption
            )
            chunks.append({
                "content":    content,
                "chunk_type": "table",
                "page":       page,
                "section":    caption,
                "image_path": None,
            })
            continue

        header_row    = md_rows[0]   # | Col1 | Col2 | ...
        separator_row = md_rows[1]   # | ---- | ---- | ...
        data_rows     = md_rows[2:]  # actual data rows

        if len(data_rows) <= TABLE_CHUNK_ROWS:
            # Small table — contextualise and keep whole
            content = _contextualise(
                f"{caption}\n\n{markdown}", parsed_doc.filename, page, caption
            )
            chunks.append({
                "content":    content,
                "chunk_type": "table",
                "page":       page,
                "section":    caption,
                "image_path": None,
            })
        else:
            # Large table — split into row groups, each with header
            for group_start in range(0, len(data_rows), TABLE_CHUNK_ROWS):
                group_rows = data_rows[group_start: group_start + TABLE_CHUNK_ROWS]
                group_md   = "\n".join([header_row, separator_row] + group_rows)
                row_range  = f"rows {group_start + 1}–{group_start + len(group_rows)}"
                group_caption = f"{caption} ({row_range})"
                raw_content   = f"{group_caption}\n\n{group_md}"

                content = _contextualise(
                    raw_content, parsed_doc.filename, page, group_caption
                )
                chunks.append({
                    "content":    content,
                    "chunk_type": "table",
                    "page":       page,
                    "section":    group_caption,
                    "image_path": None,
                })

    return chunks


def _chunk_images(image_captions: list[dict], image_save_dir: Path) -> list[dict]:
    """
    Convert image captions into contextualised chunks.

    Each chunk content is the GPT-4o generated caption, prefixed with
    document/page context for better retrieval anchoring.
    """
    chunks = []
    for cap in image_captions:
        if not cap.get("caption", "").strip():
            continue

        img_filename = f"page{cap['page']}_img{cap['index']}.png"
        image_path   = str(image_save_dir / img_filename)
        section      = f"Image on page {cap['page']}"

        # Contextualise: prefix with source doc info
        filename = image_save_dir.name   # folder name matches doc stem
        content  = _contextualise(cap["caption"], filename, cap["page"], section)

        chunks.append({
            "content":    content,
            "chunk_type": "image",
            "page":       cap["page"],
            "section":    section,
            "image_path": image_path,
        })
    return chunks


def _estimate_page(chunk_text: str, page_texts: list[str], page_nums: list[int]) -> int:
    """
    Estimate which source page a chunk came from by finding the page
    whose text has the most character overlap with the chunk.
    """
    best_page  = page_nums[0] if page_nums else 1
    best_score = 0

    # Use first 100 chars of chunk as a fingerprint
    fingerprint = chunk_text[:100]

    for page_text, page_num in zip(page_texts, page_nums):
        if fingerprint in page_text:
            return page_num
        # Count matching characters as a fallback
        score = sum(c in page_text for c in fingerprint)
        if score > best_score:
            best_score = score
            best_page  = page_num

    return best_page


def _extract_section_heading(text: str) -> str:
    """
    Best-effort extraction of a section heading from chunk text.

    Looks for lines that look like headings:
      - ALL CAPS lines
      - Numbered section patterns (e.g., "3.2 Maintenance Procedures")
      - Short first lines (< 60 chars)
    """
    lines = text.strip().split("\n")
    if not lines:
        return ""

    first_line = lines[0].strip()

    # Numbered section: "3.2 Maintenance" or "Section 4 - Safety"
    if re.match(r"^(\d+\.)+\d*\s+\w", first_line):
        return first_line[:80]

    # All caps short line
    if first_line.isupper() and len(first_line) < 60:
        return first_line

    # Short first line likely a heading
    if len(first_line) < 60 and not first_line.endswith("."):
        return first_line

    return ""
